[package]
name = "babelfont-fontc-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
babelfont = { path = "../../babelfont-rs/babelfont", features = ["fontir", "glyphs", "ufo", "fontlab", "fontforge"] }
fontc = { git = "https://github.com/googlefonts/fontc", rev = "3518040e", default-features = false }
fontbe = { git = "https://github.com/googlefonts/fontc", rev = "3518040e", default-features = false }
fontir = { git = "https://github.com/googlefonts/fontc", rev = "3518040e" }
fea-rs = "0.22.0"
fea-rs-ast = "0.1.2"
typeshare = "1.0"
kurbo = "0.13"
fontdrasil = { git = "https://github.com/googlefonts/fontc", rev = "3518040e" }
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
json-patch = "3.0"
yrs = "0.18"
console_error_panic_hook = "0.1"
tempfile = "3"
js-sys = "0.3.83"
write-fonts = { version = "0.48", features = ["read"] }
read-fonts = "0.39"
skrifa = "0.42"
smol_str = "0.3"

[dependencies.web-sys]
version = "0.3"
features = ["console"]

[profile.release]
opt-level = "z"
lto = true

[patch.crates-io]
norad = { path = "../../norad" }

[patch."https://github.com/googlefonts/fontations"]
font-types = { path = "/Users/yanone/.cargo/git/checkouts/fontations-2d2a1d0cf2f3a70a/4d690b5/font-types" }
read-fonts = { path = "/Users/yanone/.cargo/git/checkouts/fontations-2d2a1d0cf2f3a70a/4d690b5/read-fonts" }
write-fonts = { path = "/Users/yanone/.cargo/git/checkouts/fontations-2d2a1d0cf2f3a70a/4d690b5/write-fonts" }
skrifa = { path = "/Users/yanone/.cargo/git/checkouts/fontations-2d2a1d0cf2f3a70a/4d690b5/skrifa" }

[dev-dependencies]
serde_json = "1.0"
