[package]
name = "babelfont-fontc-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
babelfont = { path = "../../babelfont-rs/babelfont", features = ["fontir", "glyphs", "ufo", "fontlab", "fontforge"] }
fontc = { git = "https://github.com/simoncozens/fontc", branch = "new-varc-writefonts", default-features = false }
fontbe = { git = "https://github.com/simoncozens/fontc", branch = "new-varc-writefonts", default-features = false }
fontir = { git = "https://github.com/simoncozens/fontc", branch = "new-varc-writefonts" }
fea-rs-ast = "0.1.2"
typeshare = "1.0"
kurbo = "0.13"
fontdrasil = { git = "https://github.com/simoncozens/fontc", branch = "new-varc-writefonts" }
wasm-bindgen = "0.2"
serde_json = "1.0"
json-patch = "3.0"
yrs = "0.18"
console_error_panic_hook = "0.1"
tempfile = "3"
js-sys = "0.3.83"
write-fonts = "0.45"
read-fonts = "0.37"
skrifa = "0.28"
smol_str = "0.3"
fontspector-checkapi = "1.4.0"
fontspector-profile-opentype = "1.3.1"
fontspector-profile-universal = "1.6.0"
fontspector-profile-googlefonts = "1.6.1"
fontspector-profile-iso15008 = "1.0.5"
fontspector-profile-fontwerk = "1.2.3"

[dependencies.web-sys]
version = "0.3"
features = ["console"]

[profile.release]
opt-level = "z"
lto = true

[patch.crates-io]
norad = { path = "../../norad" }
fontspector-checkapi = { path = "vendor/fontspector-checkapi-local" }

[patch."https://github.com/googlefonts/fontations"]
font-types = { path = "/Users/yanone/.cargo/git/checkouts/fontations-2d2a1d0cf2f3a70a/cdd9351/font-types" }
read-fonts = { path = "/Users/yanone/.cargo/git/checkouts/fontations-2d2a1d0cf2f3a70a/cdd9351/read-fonts" }
write-fonts = { path = "/Users/yanone/.cargo/git/checkouts/fontations-2d2a1d0cf2f3a70a/cdd9351/write-fonts" }
skrifa = { path = "/Users/yanone/.cargo/git/checkouts/fontations-2d2a1d0cf2f3a70a/cdd9351/skrifa" }
